export const THEME = {
  THEME_COLOR: '#E0F4FF',
  COLOR_WHITE: '#fff',
  COLOR_BLACK: '#000',
  COLOR_BLUE: '#1679c9',

  PRIMARY_COLOR: '#177fdb',
  COLOR_GRAY: '#777777',
  COLOR_GRAY_LIGHT: '#DDDDDD',
  COLOR_DANGER: '#ff5b5b',
  COLOR_DANGER_DARK: '#bf2600',
  COLOR_PRIMARY: '#32921b',
  COLOR_SUCCESS: '#02b002',
  COLOR_WARNING: '#f2852a',
  COLOR_SUCCESS_LIGHT: '#A9DEAE',
  COLOR_BORDER: '#87cbcc',

  ///////////////////
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,
  FONT_WEIGHT_LIGHT: '500',
  FONT_WEIGHT_MEDIUM: '700',
  FONT_WEIGHT_BOLD: '900',
};
