export const ROUTES = {
  splash: 'Splash',
  otp: 'OTP',
  signup: 'Signup',
  drawer: 'Drawer',
  tab: 'Tab',
  home: 'Home',
  profile: 'Profile',
  about: 'About',
  dashboard: 'Dashboard',
  playlist: 'Playlist',
  playVideo: 'PlayVideo',
  login: 'Login',
  myCourse: 'My Course',
  downloads: 'Downloads',
  settings: 'Settings',
  youtube: 'Youtube',
  currentAffair: 'Current Affairs',
  news: 'News',
  syllabus: 'Syllabus',
  paidCourse: 'Paid Course',
  paidExams: 'Paid Exams',
  paidDetails: 'Paid Details',
};
