export const ROUTES = {
  splash: 'Splash',
  otp: 'OTP',
  signup: 'Signup',
  drawer: 'Drawer',
  tab: 'Tab',
  home: 'Home',
  dashboard: 'Dashboard',
  playlist: 'Playlist',
  playVideo: 'PlayVideo',
  login: 'Login',
  myCourse: 'My Course',
  downloads: 'Downloads',
  settings: 'Settings',
  youtube: 'Youtube',
};
